//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Combo.rc
//
#define IDC_DEFAULT                     3
#define IDC_ADD                         3
#define IDC_ADDMAP                      4
#define IDC_STATUS                      5
#define IDC_MAINTAB                     6
#define IDB_HELP                        17
#define IDM_HELP                        18
#define SBH                             18
#define TABH                            26
#define IDD_ABOUTBOX                    100
#define IDC_NOBK                        100
#define IDC_EDIT1                       100
#define ID_SITES_NEW                    100
#define IDC_KEY                         100
#define IDC_LINK                        100
#define IDC_RECONNECTINTERVAL           100
#define IDC_URLHEAD                     100
#define IDC_URLSCHEME                   100
#define IDC_URL_STATIC                  100
#define IDC_MAX_TRANLEN                 100
#define ID_MAINTIMER                    101
#define IDC_TRANSPARENT                 101
#define IDC_EDIT2                       101
#define ID_SITES_DEL                    101
#define URLTAIL                         101
#define IDC_NAME_STATIC                 101
#define IDC_SIDEBYSIDE                  102
#define IDC_EDIT3                       102
#define ID_SITES_NEWDIR                 102
#define IDD_GENERAL                     102
#define ID_ADD_TO_WWWHOME               103
#define IDD_MAINBAR                     103
#define IDC_CENTER                      103
#define IDC_EDIT4                       103
#define ID_SITES_EDIT                   103
#define IDC_FULL                        104
#define IDC_EDIT5                       104
#define ID_SITES_ADDFAVORITE            104
#define IDC_EDIT14                      105
#define IDC_EDIT6                       105
#define ID_SITES_UP                     105
#define IDC_EDIT15                      106
#define IDC_EDIT7                       106
#define ID_SITES_DOWN                   106
#define IDC_EDIT16                      107
#define IDC_EDIT8                       107
#define ID_SITES_EDIT2                  107
#define IDC_KEYWORD                     107
#define IDC_EDIT17                      108
#define IDC_EDIT9                       108
#define ID_SITES_ADV                    108
#define IDC_AUTO_RECONNECT              109
#define IDC_AUTORECONNECT               109
#define IDC_EDIT18                      109
#define IDC_EDIT10                      109
#define ID_SITES_ADDAUTO                109
#define IDC_COPY                        109
#define IDC_PREVENT_IDLE                110
#define IDC_EDIT19                      110
#define IDC_EDIT11                      110
#define ID_SITES_ADDHOME                110
#define IDC_EDIT20                      111
#define IDC_EDIT12                      111
#define ID_NEW_WWW2                     111
#define IDC_CUT                         111
#define IDC_SAVE                        112
#define ID_SITES_UPDATE                 112
#define IDC_CANCEL                      113
#define IDC_WWWBAR                      116
#define IDC_TOOLBAR                     117
#define IDC_CLOSEBUTTON                 118
#define IDC_PROGRESS                    119
#define IDC_HISTORYEDIT                 120
#define IDC_PASTE                       122
#define IDC_PASTE_INTO_FOLDER           123
#define IDR_MAINFRAME                   128
#define IDR_TELNETTYPE                  129
#define IDR_TABPOPUP                    129
#define IDR_POPUP                       129
#define IDD_HOST                        130
#define IDD_CONNECT                     130
#define IDD_STATUS                      131
#define IDR_TOOLBAR                     131
#define IDD_LIST                        131
#define IDD_EDITDIR                     132
#define IDD_ADLIST                      133
#define IDD_ADITEM                      134
#define IDD_WEBPAGE                     135
#define IDI_CONNECTION                  136
#define IDI_NOCONNECTION                137
#define IDC_HAND_CUR                    137
#define IDI_ACTIVE                      138
#define IDC_MYIBEAM                     138
#define IDC_DRAG                        138
#define IDC_SAVEKEY                     139
#define IDC_COPY_CUR                    139
#define IDB_TB                          140
#define IDC_ADS_COMBO                   140
#define IDC_DRAG_CUR                    140
#define IDD_CONFIG                      141
#define IDC_MAX_HISTORYMENU             141
#define IDD_COLOR                       142
#define IDC_MAX_HISTORYMENUSPIN         142
#define IDD_FORMAT                      143
#define IDD_ANSIBAR                     143
#define IDC_WEBBAR                      143
#define IDD_SETBK                       145
#define IDC_CLOSEBTNBAR                 145
#define IDC_DISABLE_POPUP               146
#define IDC_ADS_NEW                     147
#define IDC_DISABLE_SCRIPT_ERROR        148
#define IDR_WWWBAR                      149
#define IDC_IE_FAV                      149
#define IDC_AUTO_SORT                   150
#define IDB_WWWB                        151
#define IDC_AUTO_WRAP                   151
#define IDC_SEARCHBAR                   151
#define IDC_SEARCHBAR_CLEANUP           152
#define IDD_HOTSTR                      153
#define ID_MOVIETIMER                   153
#define IDD_CUSTOMIZEKEY                154
#define IDD_STRINGS                     159
#define IDI_SITE                        160
#define IDD_KEYMAP                      161
#define IDD_INPUTNAME                   165
#define IDD_QUICKCONNECT                167
#define IDR_POPUP2                      170
#define IDR_CLOSEBTN                    171
#define IDD_WEB                         173
#define IDC_TOPIC_CUR                   176
#define IDC_PAGE_CUR                    177
#define IDI_PCMAN_16                    178
#define IDI_PCMAN_96                    179
#define IDD_DOWNLOADING                 182
#define IDD_DIALOG1                     186
#define IDD_DOWNLOADING_UPDATE          186
#define IDD_INSTANT_TRAN                187
#define IDD_AUTOUPDATE                  188
#define IDI_ANSFILE                     200
#define IDD_AUTO_REPLY                  200
#define IDC_ANSIBAR_FG                  328
#define IDC_ANSIBAR_BK                  329
#define IDC_ANSIBAR_BLINK               330
#define IDC_ANSIBAR_SEND                331
#define IDC_ANSIBAR_SENDDROP            332
#define IDD_SITE                        390
#define IDD_SITE2                       391
#define IDI_DIR                         400
#define IDD_CUSTOM                      400
#define IDI_MSG                         401
#define IDD_OTHER                       401
#define IDI_EDITOR                      402
#define IDD_ESCTOOTHER                  402
#define IDI_CONNECTING                  403
#define IDD_PASSWD                      403
#define IDI_WWW                         404
#define IDD_WWWHOME                     404
#define IDD_HYPERLINK                   404
#define IDD_TRIGGER                     405
#define ID_FIRST_BBS_FAVORITE           500
#define ID_LAST_BBS_FAVORITE            1000
#define IDC_ADDRESS                     1000
#define IDC_RECONNECTSEC                1000
#define IDC_CONNECTINTERVAL             1000
#define ID_FIRST_WEB_FAVORITE           1001
#define IDC_PORT                        1001
#define IDC_INTERVAL                    1001
#define IDC_IDLEINTERVAL                1001
#define IDC_EDIT                        1001
#define IDC_LCOUNT                      1002
#define IDC_CHAR                        1003
#define IDC_STR                         1003
#define IDC_ADS                         1004
#define IDC_ONEPAGE_COL                 1004
#define IDC_ONEPAGE_LINE                1005
#define IDC_TERMTYPE                    1006
#define IDC_MAX_HISTORY                 1006
#define IDC_TITLE                       1007
#define IDC_RENAMEMAP2                  1007
#define IDC_RENAMEMAP                   1007
#define IDC_ESC_CONVERT                 1009
#define IDC_TAB                         1014
#define IDC_SITES                       1016
#define IDC_LIST                        1017
#define IDC_NAME                        1019
#define IDC_NAME2                       1020
#define IDC_URL                         1020
#define IDC_MAIL                        1025
#define IDC_WEB                         1026
#define IDC_WEB2                        1027
#define IDC_SIZER                       1031
#define IDC_CTRLU                       1042
#define IDC_DBESC                       1043
#define IDC_ESC                         1044
#define IDC_AUTOCLOSE                   1045
#define IDC_HTTP                        1046
#define IDC_FTP                         1047
#define IDC_TELNET                      1048
#define IDC_AUTOBIG5                    1049
#define IDC_AUTOLOGIN                   1050
#define IDC_AUTOCOPY                    1050
#define IDC_AUTOFONT                    1051
#define IDC_STR_TRIGGER                 1051
#define IDC_LOCALECHO                   1052
#define IDC_AUTOBIG7                    1052
#define IDC_AUTOWRAP                    1052
#define IDC_SCROLLTAB                   1053
#define IDC_LINEWRAP                    1053
#define IDC_FLASHWINDOW                 1053
#define IDC_HTTPPATH                    1054
#define IDC_USERP                       1054
#define IDC_AUTOSWITCH                  1054
#define IDC_TAB_BUTTON                  1054
#define IDC_PASSWDP                     1055
#define IDC_MINIMIZE_TO_TRAY            1055
#define IDC_WAVEPATH                    1056
#define IDC_USER                        1056
#define IDC_PASTE_AUTOWRAP              1056
#define IDC_SWITCH_BACK                 1056
#define IDC_PASSWD                      1057
#define IDC_DBLCLK_CLOSE                1057
#define IDC_AUTOJUMP                    1058
#define IDC_LINKAUTOSWITCH              1058
#define IDC_ENABLE_AUTOUPDATE           1058
#define IDC_AUTOJUMP2                   1059
#define IDC_PASTE_AUTOWRAP_COL          1060
#define IDC_AUTOJUMP3                   1060
#define IDC_SETHTTP                     1061
#define IDC_SETFTP                      1062
#define IDC_MUTE                        1063
#define IDC_PCSPEAKER                   1064
#define IDC_WAVE                        1065
#define IDC_SETWAVE                     1066
#define IDC_HOME                        1068
#define IDC_USEBK                       1069
#define IDC_ENTER                       1070
#define IDC_BACK                        1071
#define IDC_DEL                         1072
#define IDC_PATH                        1072
#define IDC_INS                         1073
#define IDC_DELMAP                      1073
#define IDC_SHOWHELP                    1073
#define IDC_PASSWORD                    1074
#define IDC_END                         1075
#define IDC_PGUP                        1076
#define IDC_PGDOWN                      1077
#define IDC_EDIT13                      1078
#define IDC_RATIO                       1078
#define IDC_BROWSE                      1080
#define IDC_TAB1                        1084
#define IDC_SPINCOL                     1086
#define IDC_SPINBUF                     1087
#define IDC_SPINLCOUNT                  1087
#define IDC_HOTKEY1                     1087
#define IDC_SPINCOL2                    1088
#define IDC_TREE1                       1088
#define IDC_TREE                        1088
#define IDC_APPLY                       1089
#define IDC_HOTKEY                      1090
#define IDC_ASSIGN                      1094
#define IDC_CHECK1                      1095
#define IDC_LINKUNDERLINE               1095
#define IDC_PROTECT                     1095
#define IDC_ANSI                        1095
#define IDC_AUTOBIG5_ARROW              1095
#define IDC_FULL_SHOWTB                 1095
#define IDC_OLD_TEXTOUT                 1095
#define IDC_CHECK2                      1096
#define IDC_LIST1                       1096
#define IDC_SHOWSCROLL                  1096
#define IDC_TABADDNUMBER                1096
#define IDC_CONTROL                     1096
#define IDC_USEURLTAIL                  1096
#define IDC_ENTER_RECONNECT             1096
#define IDC_BUTTON1                     1097
#define IDC_CHECK3                      1097
#define IDC_CLOSEQUERY                  1097
#define IDC_COLOR                       1097
#define IDC_IDLEHELP                    1097
#define IDC_FIND                        1097
#define IDC_DBLCLKSELECT                1097
#define IDC_OPEN_DLPAGE                 1097
#define IDC_BUTTON2                     1098
#define IDC_AUTOCANCELSEL               1098
#define IDC_DELPAGE                     1098
#define IDC_BBS_CLOSEQUERY              1098
#define IDC_AUTOBIG5_MOUSE              1098
#define IDC_BUTTON3                     1099
#define IDC_EXITLOG                     1099
#define IDC_NEWPAGE                     1099
#define IDC_MULTI_PCMAN                 1099
#define IDC_AUTOBIG5_DEL                1099
#define IDC_NOCON_ENTER_RECONNECT       1099
#define IDC_MODIFY                      1100
#define IDC_AUTOBIG5_BACKSPACE          1100
#define IDC_FULL_SHOWADS                1100
#define IDC_MSG                         1101
#define IDC_RENAMEPAGE                  1101
#define IDC_FULL_SHOWTAB                1101
#define IDC_RESPOND                     1102
#define IDC_FULL_SHOWSB                 1102
#define IDC_FIRST                       1103
#define IDC_FULL_USE_ANSIBAR            1103
#define IDC_COUNT                       1104
#define IDC_FULL_CLOSE                  1104
#define IDC_FULL_SHOWCLOSE              1104
#define IDC_SPINONEPAGE_COL             1105
#define IDC_FULL_SHOWWB                 1105
#define IDC_SPINONEPAGE_LINE            1106
#define IDC_FULL_SHOWSEARCH             1106
#define IDC_SPIN_MAX_HISTORY            1107
#define IDC_STATIC1                     1107
#define IDC_STATIC2                     1108
#define IDC_PAGESPIN                    1109
#define IDC_KEYLIST                     1109
#define IDC_LIST2                       1110
#define IDC_PROGRAMPATH                 1111
#define IDC_PROGRAM_PATH                1111
#define IDC_PROGRAM                     1111
#define IDC_SPIN                        1113
#define IDC_SPINAUTOWRAPCOL             1113
#define IDC_STREDIT                     1116
#define IDC_COMBO1                      1117
#define IDC_TRAN_COMB                   1117
#define IDC_TRAN_COMBO                  1117
#define IDC_COMBO2                      1118
#define IDC_KEYMAP                      1118
#define IDC_LENGTH_COMBO                1118
#define IDC_KEYMAP2                     1119
#define IDC_TRIGGER                     1119
#define IDC_TICONV                      1119
#define IDC_EDITMAP                     1120
#define IDC_ADDKEY                      1121
#define IDC_DELKEY                      1122
#define IDC_TOCONV                      1122
#define IDC_MODIFYKEY                   1123
#define IDC_TAB2                        1126
#define IDC_CONNECT                     1127
#define IDC_TAB_TEXTCOLOR               1134
#define IDC_ACTIVE_TAB_TEXTCOLOR        1134
#define IDC_ITEMSPIN                    1135
#define IDC_MAX_HISTORYSPIN             1136
#define IDC_USE_GLOBAL_SETTINGS         1137
#define IDC_VERSION                     1138
#define IDC_MAX_TRANLENSPIN             1141
#define IDR_BUILD_UI                    1234
#define IDR_MAINMENU                    1236
#define ID_LAST_WEB_FAVORITE            6000
#define ID_FIRST_HOTSTR                 6001
#define ID_LAST_HOTSTR                  8000
#define ID_SWITCHCON1                   8001
#define ID_SWITCHCON2                   8002
#define ID_SWITCHCON3                   8003
#define ID_SWITCHCON4                   8004
#define ID_SWITCHCON5                   8005
#define ID_SWITCHCON6                   8006
#define ID_SWITCHCON7                   8007
#define ID_SWITCHCON8                   8008
#define ID_SWITCHCON9                   8009
#define ID_SWITCHCON10                  8010
#define ID_ANSIPASTE_CTRLU              8011
#define ID_FIRST_ANSIPASTE              8011
#define ID_ANSIPASTE_DBESC              8012
#define ID_ANSIPASTE_ESC                8013
#define ID_LAST_ANSIPASTE               8022
#define ID_FIRST_HISTORY                8023
#define ID_LAST_HISTORY                 8037
#define ID_SITE_LIST                    32771
#define ID_CONNECT_NEW                  32772
#define ID_DISCONNECT                   32773
#define ID_CONNECT_CLOSE                32774
#define ID_FILE_EXIT                    32775
#define ID_COPY                         32776
#define ID_PASTE                        32777
#define ID_SELECTALL                    32778
#define ID_PASTEFILE                    32779
#define ID_UP                           32780
#define ID_DOWN                         32781
#define ID_BBS_FONT                     32782
#define ID_CONFIG_AUTOSWITCH            32783
#define ID_VIEW_FULLSCR                 32784
#define ID_VIEW_CONFIG                  32785
#define ID_ADDTOFAVORITE                32786
#define ID_FAVORITE_EDIT                32789
#define ID_ABOUT                        32790
#define ID_TOOL_SYMBOLS                 32791
#define ID_RECONNECT                    32792
#define ID_ANSIPASTE                    32793
#define ID_ANSICOPY                     32794
#define ID_COLORCONFIG                  32795
#define ID_ANSIEDITOR                   32796
#define ID_OPENHTML                     32797
#define ID_ANSI_SAVE                    32798
#define ID_ANSI_OPEN                    32799
#define ID_ANSI_CLS                     32800
#define ID_SEND_ANSICODE                32801
#define ID_TOOL_ANSI                    32802
#define ID_ANSI_INS                     32803
#define ID_MINIMIZE                     32804
#define ID_TOOLBAR                      32805
#define ID_STATUSBAR                    32806
#define ID_TAB                          32807
#define ID_ADS                          32808
#define ID_LEFTNODBCS                   32809
#define ID_RIGHTNODBCS                  32810
#define ID_BACKNODBCS                   32811
#define ID_SETBK                        32812
#define ID_IMPORTKKMAN                  32813
#define ID_NEW_WWW                      32814
#define ID_PGU                          32815
#define ID_PGD                          32816
#define ID_KKTAB                        32817
#define ID_WWWPREV                      32818
#define ID_WWWNEXT                      32819
#define ID_WWWSTOP                      32820
#define ID_WWWREFRESH                   32821
#define ID_WWWHOME                      32822
#define ID_ADSHTTP                      32823
#define ID_ADSTELNET                    32824
#define ID_PREVIOUS_CON                 32825
#define ID_WWW_SAVEAS                   32826
#define ID_PRINT                        32827
#define ID_PRINT_SET                    32828
#define ID_IESETUP                      32829
#define ID_WEB_FAVORITE_EDIT            32830
#define ID_WWWADDAD                     32831
#define ID_AD                           32832
#define ID_CLEAR_HISTORY                32833
#define ID_CUSTOMIZE                    32834
#define ID_AUTO_DBCS                    32835
#define ID_SHOW_SCROLL                  32836
#define ID_IDLE_HELP                    32836
#define ID_FREQ_STR                     32837
#define IDC_MAKE_DEFAULT                32838
#define ID_AUTOSORT_FAVORITE            32839
#define ID_SETDEFAULT                   32840
#define ID_COPYPASTE                    32841
#define ID_ESCTOOTHER                   32842
#define ID_PROTECT                      32843
#define ID_SMOOTH_DRAW                  32844
#define ID_ANSI_SAVEAS                  32845
#define ID_INTRODUCE                    32846
#define IDM_HELP2                       32847
#define ID_ADDTOHOME                    32848
#define ID_SET_HOTKEY                   32849
#define ID_SELALL_BUF                   32850
#define ID_HOME                         32851
#define ID_NEW_HOME                     32852
#define ID_NEW_CURPAGE                  32853
#define ID_NEW_BLANK                    32854
#define ID_ADSFOCUS                     32855
#define ID_EDIT_WWWHOME                 32856
#define ID_WWW_FIND                     32857
#define ID_VIEW_SRC                     32858
#define ID_WEBPAGE_VIEWSRC              32858
#define ID_BLOCK_POPUP                  32859
#define ID_ADS_OPENNEW                  32860
#define ID_EXITLOG                      32861
#define ID_LASTCON                      32862
#define ID_AUTODBCS_ARROW               32870
#define ID_AUTODBCS_MOUSE               32871
#define ID_AUTODBCS_BACKSPACE           32872
#define ID_AUTODBCS_DEL                 32873
#define ID_CURCON_SETTINGS              32874
#define ID_EDIT_COPYURL                 32876
#define ID_UPDATE_BBSLIST               32884
#define ID_GET_LOCALIP                  32885
#define ID_CUSTOMIZE_MAINTB             32886
#define ID_BACKUP_CONFIG                32887
#define ID_EDIT_OPENURL                 32888
#define ID_EDIT_OPENURL_HTTP            32889
#define ID_EDIT_OPENURL_TELNET          32890
#define ID_EDIT_OPENURL_FTP             32891
#define ID_TOOL_LOCK                    32892
#define ID_SEND_FG                      32893
#define ID_SEND_BK                      32894
#define ID_SEND_RESETCLR                32895
#define ID_FAVORITE_OPENALL             32897
#define ID_SITE_MOVE_INTO_FOLDER        32898
#define ID_SITE_MOVE_TO_HERE            32899
#define ID_FONT_SMALLEST                32901
#define ID_FONT_SMALL                   32902
#define ID_FONT_MEDIUM                  32903
#define ID_FONT_LARGE                   32904
#define ID_FONT_LARGEST                 32905
#define ID_TOOL_IMPORT_2003             32907
#define ID_TOOL_IMPORT_IEFAV            32908
#define ID_GOBACK                       32909
#define ID_GOFORWARD                    32910
#define ID_CLOSEBTN                     32913
#define ID_WEBBAR                       32914
#define ID_CUSTOMIZE_WB                 32915
#define ID_TOOL_EXPORT_IEFAV            32916
#define ID_WEBPAGE_SAVEAS               32917
#define ID_WEBPAGE_OPEN                 32918
#define ID_WEBPAGE_PRINTSETTINGS        32919
#define ID_WEBPAGE_PRINT                32920
#define ID_WEBPAGE_ADDAD                32921
#define ID_NEW_IE_CURPAGE               32922
#define IDS_SEARCH_BAR_TITLE            32922
#define ID_SWITCH_BACK                  32923
#define ID_SEARCHBAR_FOCUS              32924
#define ID_PASTETINYURL                 32926
#define ID_SEARCHBAR                    32927
#define ID_COPYARTICLE                  32928
#define ID_PLAY_ANSIMOVIE               32929
#define IDS_ERR                         32929
#define IDS_CONFIM_PASSWD2              32930
#define ID_DOWNLOAD_ARTICLE             32930
#define IDS_DIFF_PASSWD                 32931
#define ID_COPYARTICLE_WITH_ANSI        32931
#define ID_FONT_BTN                     32932
#define IDS_INCOMPLETE_AUTO_SETTINGS    32933
#define ID_EDIT_DELETE                  32933
#define IDS_SAVE_BTN                    32934
#define ID_EDIT_SELALL                  32934
#define IDS_CANCEL_BTN                  32935
#define IDS_CANCEL_BTN2                 32936
#define IDS_DEL_CONFIRM                 32937
#define IDS_CONFIRM                     32938
#define IDS_ADD_BTN                     32939
#define IDS_MODIFY_BTN                  32940
#define IDS_DEL_BTN                     32941
#define IDS_PASSWD_ERR                  32942
#define IDS_AUTO_HELP                   32943
#define IDS_HELP                        32944
#define IDS_OLD_PASSWD                  32945
#define IDS_NEW_PASSWD                  32946
#define IDS_REPLACE_OLD_HOTKEY_CONFIRM  32947
#define IDS_NOT_ASSIGNED                32948
#define IDS_NONE                        32949
#define IDS_HYPERLINK                   32950
#define IDS_OPEN_PROGRAM                32951
#define IDS_MODIFY_BTN2                 32952
#define IDS_EXE_FILTER                  32953
#define IDS_DEFAULT_KEYMAP              32954
#define IDS_ALL_EMPTY_DISALLOWED        32955
#define IDS_CUSTOMIZE_TOOLBAR           32956
#define IDS_SEPARATOR                   32957
#define IDS_KEYBOARD_KEY                32958
#define IDS_CONFIG_OF_KEY               32959
#define IDS_EDIT_KEY_MAP_TITLE          32960
#define IDS_SETTINGS_INCOMPLETE         32961
#define IDS_SPECIFIED_KEY_EXISTS        32962
#define IDS_SITE_SETTINGS               32963
#define IDS_NOT_FOUND                   32964
#define IDS_SEARCH_RESULT               32965
#define IDS_ADS_BAR_TITLE               32966
#define IDS_EXIT_CONFIRM                32967
#define IDS_CON_STATUS                  32968
#define IDS_ANSIED_STATUS               32969
#define IDS_INSERT                      32970
#define IDS_REPLACE                     32971
#define IDS_NOT_SAVED                   32972
#define IDS_CLOSE_THIS_PAGE             32973
#define IDS_SET_DEFALT_TELNET           32974
#define IDS_SET_DEFAULT_BROWSER         32975
#define IDS_SET_TO_DEFAULT_ANS          32976
#define IDS_WEBPAGE_FILTER              32977
#define IDS_LOCAL_IP                    32978
#define IDS_CHOOSE_BACKUP_DIR           32979
#define IDS_CHOOSE_2003_DIR             32980
#define IDS_IMPORT_IE_FAV               32981
#define IDS_IMPORT_IE_FAV_PROMPT        32982
#define IDS_IMPORT_COMPLETE             32983
#define IDS_FINISHED                    32984
#define IDS_EXPORT_COMPLETE             32985
#define IDS_CLOSE_CONFIRM               32986
#define IDS_CON_FAILED                  32987
#define IDS_CHOOSE_BACKGROUND           32988
#define IDS_BMP_FILTEER                 32989
#define IDS_DONT_USE                    32990
#define IDS_GB2BIG5                     32991
#define IDS_BIG52GB                     32992
#define IDS_IDLE_HELP                   32993
#define IDS_UNABLE_TO_DEL_KEYMAP        32994
#define IDS_FREQ_USED_TEXT              32995
#define IDS_HOTKEY                      32996
#define IDS_NOT_INPUT_YET               32997
#define IDS_DEL_PAGE_CONFIRM            32998
#define IDS_IMPORTANT_FILE_LOST         32999
#define IDS_DEFAULT_FONT_FACE           33000
#define IDS_DOUBLE_SPACE_CHAR           33001
#define IDS_TXT_FILTER                  33002
#define IDS_PCMAN_ALL_SETTINGS          33003
#define IDS_SET_FONT_PROMPT             33004
#define IDS_ATTENTION                   33005
#define IDS_TAB_STYLE_ERR_MSG           33006
#define IDS_ANSI_EDIT                   33007
#define IDS_ANS_FILTER                  33008
#define IDS_TXT_AND_ANS_FILTER          33009
#define IDS_LOAD_PIC_FAILED             33010
#define IDS_CLEAR_ADS_CONFIRM           33011
#define IDS_CLEAR_HISTORY_CONFIRM       33012
#define IDS_SMOOTH_DRAW_INFO            33013
#define IDS_FIND_IN_ALL_BUF             33014
#define IDS_CUR_CON_SETTINGS            33015
#define IDS_BBS_LIST_NAME               33016
#define IDS_HOMEPAGE_NAME               33017
#define IDS_BBS_FAVORITE_NAME           33018
#define IDS_WWW_FAVORITE_NAME           33019
#define IDS_COPY_URL                    33020
#define IDS_ABOUT_INFO                  33021
#define IDS_TEST                        33021
#define IDS_WAV_FILTER                  33022
#define IDS_SITELIST_UPDATE_SUCCESS     33023
#define IDS_SITELIST_UPDATE_FAIL        33024
#define ID_SET_CHARSET_DEFAULT          33025
#define IDS_WEB_SEARCH                  33025
#define ID_SET_CHARSET_CP950            33026
#define ID_SET_CHARSET_CP936            33027
#define ID_SET_CHARSET_CP932            33028
#define ID_SET_CHARSET_UTF8             33029
#define ID_WEB_SEARCH                   33030
#define IDS_PROMPT_IMPORT               33031
#define ID_MOUSE_CTL                    33032
#define IDS_PCMAN_CLOSE                 33032
#define ID_AUTO_UPDATE                  33033
#define IDS_INSTALL_UPDATE              33033
#define IDS_MOUSE_GESTURE               33034
#define IDS_UNKNOWN_GESTURE             33035
#define ID_INSTANT_TRAN                 33036
#define IDS_TRANSLATION                 33036
#define ID_CHECK_UPDATE                 33037
#define ID_NCIKU                        33039
#define ID_WIKIPEDIA                    33040
#define ID_SEARCHBAR_CLEANUP            33040
#define IDS_CLOSE_ALL_OTHER_PAGES       33041
#define ID_CONNECT_CLOSE_ALL_OTHERS     33042

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        189
#define _APS_NEXT_COMMAND_VALUE         33041
#define _APS_NEXT_CONTROL_VALUE         1142
#define _APS_NEXT_SYMED_VALUE           154
#endif
#endif
